name: RecentPapers

on:
  schedule:
    - cron: "0 9 * * *"
    
jobs:
  recent-papers:
    name: recent-papers    # 省略可能
    runs-on: ubuntu-latest
    steps:
      - name: exec recent papers
      run: echo "exec recent papers"
      
      
      
    
  
